apiVersion: vm.rancher.com/v1alpha1
kind: Credential
metadata:
  name: james
spec:
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0JXJ5BmKNHLDQGDK0SpyeNbl+DOaKcVLE/yoNl6YxMxehQ36HxudmyPWV0jk7hMkrLugklGtcyQZFtp/A9YWSycarfHE89B6IYxbDPir3NTChGtMIzc3MvxrBPNmKTo3MKqZyB+ZRmyvy+F5OoKS9P4Tk9guBuRnseyNvq2bfoekang+hlWw6ksgwtKsiTJjSrW9+96Z/0KNNcD3eDUexQIyuALWz0fYAvNZAfZXgd0GJ63OiwJ3nTcoWAso2NmRR5WSTjlV85ZmEUPWExLBrxVmx/JvDFI+V6PpYIbtY3gTzpqUNK3hqN9yS8ZQc7dngZWc6VFwA5tFFGAChs1TJ joliver@Jamess-MacBook-Pro.local
---
apiVersion: vm.rancher.com/v1alpha1
kind: Credential
metadata:
  name: jimmy
spec:
  public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDumacMhJueiALra29ETZLVRpLYlMn+S1/wOVQ9oJEOwvG656eRX7dn49oFTzJQWwvPi3DpwfNALkxMuGCMGYLYZlATTQP+qn6T7JZcIL3ulf8/6qh66LXq64ZcktAs4PxrrEJhsoJusAa6Nex3doQ7hG++UXsQRFiS9oss32J+nWdYIrJH7tLvFKeMKNCv24AqhH/b3Q0aE8tsPuQLmlNyE2eVQ8DHCaVG94kKvCRxJizy0X4hHhQrnU29t24wRk4GqRAkE75Q8jFVBTDjyg9MSzI24uRmD0dnMOD7cKILwX0a0lA2oiMuKNPKOE4HOLvf6RiA/j7r8sJ8iB9cod49 joliver@Jamess-MBP.tempe.rancherlabs.com
