apiVersion: v1
kind: Namespace
metadata:
  name: james
---
apiVersion: vm.rancher.com/v1alpha1
kind: VirtualMachine
metadata:
  namespace: james
  name: example
spec:
  cpu_milli: 1000
  memory_mb: 1024
---
apiVersion: v1
kind: Namespace
metadata:
  name: murali
---
apiVersion: vm.rancher.com/v1alpha1
kind: VirtualMachine
metadata:
  namespace: murali
  name: example
spec:
  cpu_milli: 2000
  memory_mb: 4096
